---
version: "2.1"
services:
  code-server:
    image: itchi/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DOCKER_MODS=linuxserver/mods:code-server-awscli|linuxserver/mods:code-server-golang|linuxserver/mods:code-server-extension-arguments
      - VSCODE_EXTENSION_IDS=hashicorp.terraform|mauve.terraform|ms-python.python|ms-toolsai.jupyter|janisdd.vscode-edit-csv
    volumes:
      - C:\path\to\workfolder:/config
    ports:
      - 8443:8443
    restart: unless-stopped